# Generated by Django 4.1.2 on 2022-10-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itemgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_delivered',
        ),
    ]
