# Generated by Django 4.1.2 on 2022-10-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_option_table_alter_item_genre_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
    ]
